services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      # Puxa as definições do seu arquivo .env automaticamente
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - rede-governance

  api:
    build: ./backend-node
    container_name: node_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_DIALECT=postgres
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    networks:
      - rede-governance

  frontend:
    build: 
      context: ./frontend
      # Passa a URL da API para o Vite durante o build
      args:
        - VITE_API_URL=http://34.95.207.232:3000/api
    container_name: react_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://34.95.207.232:3000/api
    networks:
      - rede-governance

networks:
  rede-governance:
    driver: bridge