import type { PermissionsMap } from '../types/permissions';

export const roleTemplates: Record<string, PermissionsMap> = {
  Administrator: {
    dashboard: 'edit',
    inventory: 'edit',
    employees: 'edit',
    contracts: 'edit',
    catalog: 'edit',
    licenses: 'edit',
    maintenance: 'edit',
    offboarding: 'edit',
    import: 'edit',
    export: 'edit',
    admin: 'edit',
    settings: 'edit',
  },
  Gestor: {
    dashboard: 'read',
    inventory: 'read',
    employees: 'read',
    contracts: 'read',
    catalog: 'read',
    licenses: 'read',
    maintenance: 'read',
    offboarding: 'read',
    import: 'none',
    export: 'edit',
    admin: 'none',
    settings: 'none',
  },
  'Analista de Contrato': {
    dashboard: 'read',
    inventory: 'none',
    employees: 'none',
    contracts: 'edit',
    catalog: 'edit',
    licenses: 'edit',
    maintenance: 'none',
    offboarding: 'none',
    import: 'none',
    export: 'none',
    admin: 'none',
    settings: 'none',
  },
  'Analista N1': {
    dashboard: 'read',
    inventory: 'edit',
    employees: 'edit',
    contracts: 'none',
    catalog: 'read',
    licenses: 'none',
    maintenance: 'edit',
    offboarding: 'edit',
    import: 'none',
    export: 'none',
    admin: 'none',
    settings: 'none',
  },
  'Analista N2': {
    dashboard: 'read',
    inventory: 'none',
    employees: 'none',
    contracts: 'none',
    catalog: 'read',
    licenses: 'none',
    maintenance: 'none',
    offboarding: 'none',
    import: 'edit',
    export: 'edit',
    admin: 'none',
    settings: 'none',
  },
};

