name: Deploy API Inventario no Google Cloud

on:
  push:
    branches:
      - main
      - master

# Adicionamos a variável global para forçar os robôs do GitHub a usarem a versão atualizada
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: Deploy para a VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Copiar arquivos para o Servidor via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend-node,frontend,dados,docker-compose.yml"
          target: "~/IT_Governance"

      - name: Executar build e deploy via SSH no Servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/IT_Governance
            
            # Derruba os containers antigos
            sudo docker-compose down
            
            # Sobe os containers novamente recriando a imagem da API e do Frontend
            sudo docker-compose up -d --build
            
            # Limpa imagens antigas e órfãs para não lotar o disco do servidor
            sudo docker image prune -f